version: '3.9'

services:

  postgres:
    image: postgres:16-alpine
    container_name: fsdo-db
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fsdo-backend
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/appdb
      DB_USER: admin
      DB_PASS: secret
      SPRING_PROFILES_ACTIVE: dev
      APP_ENV: dev
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fsdo-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: fsdo-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus-local.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:10.4.0
    container_name: fsdo-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: "false"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

  loki:
    image: grafana/loki:3.0.0
    container_name: fsdo-loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:3.0.0
    container_name: fsdo-promtail
    volumes:
      - /var/log:/var/log
      - ./monitoring/promtail-local.yml:/etc/promtail/config.yml
    depends_on:
      - loki

volumes:
  postgres_data:
  grafana_data:
