apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  APP_ENV: "qa"
  SPRING_PROFILES_ACTIVE: "qa"
  DB_URL: "jdbc:postgresql://klauz-dev-db.postgres.database.azure.com:5432/appdb"
  DB_USER: "klauzadmin"
  DB_POOL_SIZE: "8"
