apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  APP_ENV: "prod"
  SPRING_PROFILES_ACTIVE: "prod"
  DB_URL: "jdbc:postgresql://klauz-prod-db.postgres.database.azure.com:5432/appdb"
  DB_USER: "klauzadmin"
  DB_POOL_SIZE: "20"
