apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: klauz-prod

resources:
  - ../../base
  - namespace.yaml

patches:
  - path: backend-patch.yaml
    target:
      kind: Deployment
      name: backend
  - path: frontend-patch.yaml
    target:
      kind: Deployment
      name: frontend
  - path: configmap.yaml
    target:
      kind: ConfigMap
      name: backend-config
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: klauz-ingress

images:
  - name: klauzdevacr.azurecr.io/backend
    newName: klauzdevacr.azurecr.io/backend
    newTag: sha-d315f842999db191b430d9251b7d00d2e759909b
  - name: klauzdevacr.azurecr.io/frontend
    newName: klauzdevacr.azurecr.io/frontend
    newTag: sha-d315f842999db191b430d9251b7d00d2e759909b

commonLabels:
  environment: prod
